import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/Layouts/NavBar";
import { Providers } from "./Provider";
import Footer from "./Components/Layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <header className="sticky top-0 z-50">
            <NavBar></NavBar>
          </header>
          <main className="md:max-w-300 mx-auto min-h-[calc(100svh-302px)]">
            {children}
          </main>
          <footer>
            <Footer></Footer>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
