import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../Layouts/NavBar";
import { Providers } from "./(dashboard)/dashboard/Provider";
import Footer from "../Layouts/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { ToastContainer, Zoom } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Care.IO Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Providers>
            <main>
              <ToastContainer
                position="top-center"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="dark"
                transition={Zoom}
              />
              {children}
            </main>
          </Providers>
        </body>
      </html>
    </NextAuthProvider>
  );
}
